#!/usr/bin/bash

# LainOS Orginal Program 227865 2022
# This Project Writed for help you to Install Other Programs
# Writer : Wired
# ---- For LainOS Team ----

VERSION="1.2.0"
NAME="LainOS LPD Package Downloader"
OS='LainOS'
IFS=';'

function echo_title() {     echo -ne "\033[1;44;37m${*}\033[0m\n"; }
function echo_caption() {   echo -ne "\033[0;1;44m${*}\033[0m\n"; }
function echo_bold() {      echo -ne "\033[0;1;34m${*}\033[0m\n"; }
function echo_danger() {    echo -ne "\033[0;31m${*}\033[0m\n"; }
function echo_success() {   echo -ne "\033[0;32m${*}\033[0m\n"; }
function echo_warning() {   echo -ne "\033[0;33m${*}\033[0m\n"; }
function echo_secondary() { echo -ne "\033[0;34m${*}\033[0m"; }
function echo_info() {      echo -ne "\033[0;35m${*}\033[0m\n"; }
function echo_primary() {   echo -ne "\033[0;36m${*}\033[0m\n"; }
function echo_error() {     echo -ne "\033[0;1;31merror:\033[0;31m\t${*}\033[0m\n"; }
function echo_label() {     echo -ne "\033[0;1;32m${*}:\033[0m\t"; }
function echo_prompt() {    echo -ne "\033[0;36m${*}\033[0m "; }
function splash() {
    local hr
    hr=" **$(printf "%${#1}s" | tr ' ' '*')** "
    echo_title "${hr}"
    echo_title " * $1 * "
    echo_title "${hr}"
    echo
}

function echo_test(){
	echo_title title
	echo_caption caption
	echo_bold bold
	echo_danger danger
	echo_success success
	echo_warning warning
	echo_primary primary
	echo_secondary secondary
	echo_info info
	echo_label label
	echo_error error
	echo_prompt prompt
	splash splash
}
#echo_test

function select_option {

    ESC=$( printf "\033")
    cursor_blink_on()  { printf "$ESC[?25h"; }
    cursor_blink_off() { printf "$ESC[?25l"; }
    cursor_to()        { printf "$ESC[$1;${2:-1}H"; }
    print_option()     { printf "$1 "; }
    print_selected()   { printf "$ESC[7m$1 $ESC[27m"; }
    get_cursor_row()   { IFS=';' read -sdR -p $'\E[6n' ROW COL; echo ${ROW#*[}; }
    key_input()        { read -s -n3 key 2>/dev/null >&2
                         if [[ $key = $ESC[A ]]; then echo up;    fi
                         if [[ $key = $ESC[B ]]; then echo down;  fi
                         if [[ $key = ""     ]]; then echo enter; fi; }

    for opt; do printf "\n"; done

    local lastrow=`get_cursor_row`
    local startrow=$(($lastrow - $#))

    trap "cursor_blink_on; stty echo; printf '\n'; exit" 2
    cursor_blink_off

    local selected=0
    while true; do
        local idx=0
        for opt; do
            cursor_to $(($startrow + $idx))
            if [ $idx -eq $selected ]; then
                print_selected "$opt"
            else
                print_option "$opt"
            fi
            ((idx++))
        done

        case `key_input` in
            enter) break;;
            up)    ((selected--));
                   if [ $selected -lt 0 ]; then selected=$(($# - 1)); fi;;
            down)  ((selected++));
                   if [ $selected -ge $# ]; then selected=0; fi;;
        esac
    done

    cursor_to $lastrow
    printf "\n"
    cursor_blink_on

    return $selected
}

function select_opt {
    select_option "$@" 1>&2
    local result=$?
    echo $result
    return $result
}

function patch_adder()
{
	if [ -f "$(pwd)/$1" ]; then
		path=$1
	else
		if [ -f "$(pwd)/PDLP/$1" ]; then
			path="PDLP/$1"
		else
			echo "your file is not found !"
			return 0;
		fi
	fi	
	# file_name=$(cat $path | grep "name" | tr " " " ")
	file_name=$(sed -n 1p $path)
	file_name_org=${file_name:7}
	
	pfiles=$(sqlite3 mainsb "SELECT name FROM cus_prg")
	mapfile pars_names <<< "$pfiles"
	for ((a = 0; a < ${#pars_names[@]}; a++))
	{
		org=${pars_names[$a]};
		if [[ $file_name_org == ${org:0:-1} ]]; then
			echo_danger "you have already had $file_name_org this file !"
			return 1;
		fi
	}

	code=$(cat $path | sed '/^[[:space:]]*$/d')
	mapfile -t data <<< "$code"
	for ((i = 2; i < ${#data[@]}; i++))
	{
		if [[ ${data[$i]} != "" ]]; then
			org+="${data[$i]};"
		fi
	}
	sqlite3 mainsb "insert into cus_prg values ('$file_name_org', 'This is new Program for new mode in PDL', '$org');"
	echo_success "[+] The $1 patch file was applied"
	org=""
}

cust=()
$selc;
$pck_name;
$str;
splash "LainOS PRGD - V$VERSION"

function pe() {
    dpkg -s "$1" &> /dev/null
    return $?
}

function help()
{
	echo_caption "-- LainOS Package Downloader LainOS (PDL) Version $VERSION --"
	echo
	echo_primary "Description :"
	echo_secondary "	This tool helps you to download and install packages that you can see in APT-REP or GIT-REP\n"
	echo_secondary "  	We use Save installer commands into a database and you can install all packages with one click\n"
	echo_secondary "	You should have GIT for download from github\n"
	echo_secondary "	Is git available? "
	if pe "git"; then
		echo_success "Yes!"
	else
		echo_danger "No!"
	fi
	echo
	echo "-------------"
	echo_primary "Arguments :"
	echo_secondary "-h/--help         "; echo_info "help command"
	echo_secondary "-p         	  "; echo_info "add patch file to PDL"
	echo_secondary "-n         	  "; echo_info "install normal level programs"
	echo_secondary "-c         	  "; echo_info "install compile level programs"
	echo_secondary "-i         	  "; echo_info "install custom programs"
	echo_secondary "-l		  "; echo_info "list all programs and PDL patch files that currently PDL have"
	echo_secondary "-u/--update       "; echo_info "update patch files from PDLP git repository"
} 

function comp_inst()
{
	data=($(sqlite3 mainsb 'select name from comp_prg'))
	mapfile -t arr7 <<< "$data"
	for ((i = 0; i < ${#arr7[@]}; i++))
	{
		if pe ${arr7[$i]}; then
			echo_warning "[!] You already have ${arr7[$i]} package installed!"
		else
			eval "sudo apt install ${arr7[$i]}"
		fi
	}
}

function norm_inst()
{
	data2=($(sqlite3 mainsb 'select name from norm_prg'))
	mapfile -t arr5 <<< "$data2"
	for ((i = 0; i < ${#arr5[@]}; i++))
	{
		if pe ${arr5[$i]}; then
			echo_warning "[!] You already have ${arr5[$i]} package installed!"
		else
			eval "sudo apt install ${arr5[$i]}"
		fi
	}
}

function customize_installation()
{
	local t=$1
	echo "[+] $t item is added to your program list ."
	cust+=($t)
}

function custom()
{
	data_name=($(sqlite3 mainsb "select name from cus_prg"))
	mapfile -t dnc <<< "$data_name"
	for ((o = 0; o < ${#dnc[@]}; o++))
	do
		if [[ ${dnc[$o]} == $1 ]]; then
			data_code=$(sqlite3 mainsb "select code from cus_prg where name='$1'")
			read -a str <<< "$data_code"
			break
		fi
	done
	for ((i = 0; i < ${#str[@]}; i++))
	do
		echo "[!] Executing: ${str[$i]}"
		eval ${str[$i]}
	done
}

function GetCount(){
	norm_count=($(sqlite3 mainsb "select name from norm_prg"))
	comp_count=($(sqlite3 mainsb "select name from comp_prg"))
	cus_count=($(sqlite3 mainsb "select name from cus_prg"))
	mapfile -t ncc <<< "$norm_count"		
	mapfile -t ccc <<< "$comp_count"
	mapfile -t cucc <<< "$cus_count"
}
GetCount

function net()
{
	if pe "git"; then
		echo
	else
		echo_error "you don't have git, first you should install git ..."
		return 0;
	fi

	git clone "https://github.com/ashk123/PDLP.git" -q
	file=$(ls PDLP)
	mapfile -t files <<< "$file"
	for ((a = 0; a < ${#files[@]}; a++))
	do
		stext=${files[$a]}
		slen=${#files[$a]}
		if [[ ${stext:$((slen - 3)):3} != "pdl" ]]; then
			echo_danger "you can't any file type !";
		else
			patch_adder ${files[$a]}
			#echo "[+] Patch ${files[$a]} Install"
		fi
	done
	rm -rf PDLP
}

function choos_item_cust()
{
	cust_names=($(sqlite3 mainsb "select name from cus_prg"))
	mapfile -t arr3 <<< "$cust_names"
	echo "$1"
}

function custom_menu()
{
	echo_label "\nyou have these options";
	echo ""
	custs=()
	cust_names=($(sqlite3 mainsb "select name from cus_prg"))
	mapfile -t arr3 <<< "$cust_names"
	for ((i3 = 0; i3 < ${#arr3[@]}; i3++))
	do
		echo_secondary "$((i3 + 1)) - ${arr3[$i3]}\n"
		custs+=(${arr3[$i3]})
	done
	echo ""
	read -p "Package Name: " pck_name
	case $pck_name in
		''|*[!0-9]*)
			echo_error "not a number"
		;;
		*)
			num=$((pck_name - 1))
			custom ${custs[num]}
		;;
	esac
}

function prg_list()
{
	data_name=($(sqlite3 mainsb "select name from cus_prg"))
	mapfile -t prg_names <<< "$data_name"
	for ((a = 0; a < ${#prg_names[@]}; a++))
	{
		echo "$((a + 1)) - ${prg_names[$a]}"
	}
	data_name=($(sqlite3 mainsb "select name from norm_prg"))
	mapfile -t norm_names <<< "$data_name"
	for ((b = 0; b < ${#norm_names[@]}; b++))
	{
		echo "$((a + 1)) - ${norm_names[$b]}"
		a=$a+1
	}
	data_name=($(sqlite3 mainsb "select name from comp_prg"))
	mapfile -t comp_names <<< "$data_name"
	for ((c = 0; c < ${#comp_names[@]}; c++))
	{
		echo "$((a + 1)) - ${comp_names[$c]}"
		a=$a+1
	}
	echo
	echo "Total: $((a))"
}

function cus_remove()
{
	# Sql-Injection Zone - we should check value or better way use regex
	sqlite3 mainsb "delete from cus_prg where name = '$1'"
	echo "[+] Package $1 is remove from custome packages"
}

function main_menu()
{
	echo ""
	echo_primary "1. Normal installation (${#ncc[@]})"
	echo_primary "2. Compilers           (${#ccc[@]})"
	echo_primary "3. Custom list         (${#cucc[@]})"
	#echo_primary "LainOS Package Downloader V$VERSION"
}

if [ -z "$*" ] || [ $1 == "-s" ]; then
	#main_menu

	while [ true ]
	do
		GetCount
		main_menu
		read -p ": " selc
		if [[ $selc == "h" ]]; then
			help;
		elif [[ $selc == "1" ]]; then
			norm_inst;
		elif [[ $selc == "2" ]]; then
			comp_inst;
		elif [[ $selc == "3" ]]; then
			custom_menu
		elif [[ $selc == "list 1" ]] || [[ $selc == "l 1" ]]; then
			echo_primary "\n-- Normal installation packages --"
			data=($(sqlite3 mainsb 'select name from norm_prg'))
			mapfile -t arr2 <<< "$data"
			for ((i4 = 0; i4 < ${#arr2[@]}; i4++))
			do
				echo_secondary "[+] Package ${arr2[$i4]}\n"
			done
		elif [[ $selc == "list 2" ]] || [[ $selc == "l 2" ]]; then
			echo_primary "\n-- Compilers installation packages --"
			data2=($(sqlite3 mainsb 'select name from comp_prg'))
			mapfile -t arr <<< "$data2"
			for ((i2 = 0; i2 < ${#arr[@]}; i2++))
			do
				echo_secondary "[+] Package ${arr[$i2]}\n"
			done
		elif [[ $selc == "exit" ]] || [[ $selc == "q" ]]; then
			break
		elif [[ $selc == "version" ]]; then
			echo $VERSION
		elif [[ $selc == "os" ]]; then
			echo $OS
		else
			echo "Please enter a valid option."
		fi
	done
	
elif  [ $1 == "-m" ]; then
	options=("1. Normal installation (${#ncc[@]})" "2. Compilers           (${#ccc[@]})" "3. Custom list         (${#cucc[@]})")
	case `select_opt "${options[@]}"` in
	    0) norm_inst;;
	    1) comp_inst;;
	    2) custom_menu;;
	esac
elif [ $1 == "--help" ] || [ $1 == "-h" ]; then
	help
elif [ $1 == "-p" ]; then
	patch_adder $2
elif [ $1 == "-u" ] || [ $1 == "--update" ]; then
	net
elif [ $1 == "-n" ]; then
	norm_inst
elif [ $1 == "-c" ]; then
	comp_inst
elif [ $1 == "-i" ]; then
	custom $2
elif [ $1 == "-l" ]; then
	prg_list
elif [ $1 == "-r" ]; then
	cus_remove $2
else
	echo "This command is not found !, try ./main --help"
fi
